language: python
python:
  - '2.7'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers cmake
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


  - export PYTHON_VERSION=$(python -c 'import sys; print(sys.version_info[0:2])')
  - pip install -r requirements.txt
  - pip install coveralls coverage
  - ./bin/build_clBLAS.sh
script:
  - nosetests --verbose --with-coverage --cover-package=hindemith
  - mv .coverage .coverage.1
  - CC=gcc HM_BACKEND=omp nosetests --verbose --with-coverage --cover-package=hindemith --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_hindemith_f979e4371d_0
  - python -m properform Push 47.88.50.110:15554 asdf_hindemith_f979e4371d_0 ./profile_hindemith_f979e4371d_0


  - mv .coverage .coverage.2
  - coverage combine
 #2017-09-14 12:28:48 modified at 0